### ISSUE TITLE
Can't build with rust-1.51.0

### ISSUE THREAD

**Issue by crocket** [PirateNetwork/PirateWallet-Lite#30]
```
error[E0277]: cannot multiply-assign `<E as ScalarEngine>::Fr` by `&&<E as ScalarEngine>::Fr`
   --> /var/tmp/portage/net-p2p/piratewallet-lite-1.0.4/work/cargo_home/gentoo/bellman-0.6.0/src/gadgets/test/mod.rs:131:24
    |
131 |         tmp.mul_assign(&coeff);
    |                        ^^^^^^ no implementation for `<E as ScalarEngine>::Fr *= &&<E as ScalarEngine>::Fr`
    |
    = help: the trait `MulAssign<&&<E as ScalarEngine>::Fr>` is not implemented for `<E as ScalarEngine>::Fr`
help: consider further restricting the associated type
    |
122 | ) -> E::Fr where <E as ScalarEngine>::Fr: MulAssign<&&<E as ScalarEngine>::Fr> {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0277]: cannot multiply-assign `<E as ScalarEngine>::Fr` by `&&<E as ScalarEngine>::Fr`
   --> /var/tmp/portage/net-p2p/piratewallet-lite-1.0.4/work/cargo_home/gentoo/bellman-0.6.0/src/groth16/generator.rs:389:39
    |
389 |                         at.mul_assign(&beta);
    |                                       ^^^^^ no implementation for `<E as ScalarEngine>::Fr *= &&<E as ScalarEngine>::Fr`
    |
    = help: the trait `MulAssign<&&<E as ScalarEngine>::Fr>` is not implemented for `<E as ScalarEngine>::Fr`
help: consider further restricting the associated type
    |
324 |     ) where <E as ScalarEngine>::Fr: MulAssign<&&<E as ScalarEngine>::Fr> {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0277]: cannot multiply-assign `<E as ScalarEngine>::Fr` by `&&<E as ScalarEngine>::Fr`
   --> /var/tmp/portage/net-p2p/piratewallet-lite-1.0.4/work/cargo_home/gentoo/bellman-0.6.0/src/groth16/generator.rs:390:39
    |
390 |                         bt.mul_assign(&alpha);
    |                                       ^^^^^^ no implementation for `<E as ScalarEngine>::Fr *= &&<E as ScalarEngine>::Fr`
    |
    = help: the trait `MulAssign<&&<E as ScalarEngine>::Fr>` is not implemented for `<E as ScalarEngine>::Fr`
help: consider further restricting the associated type
    |
324 |     ) where <E as ScalarEngine>::Fr: MulAssign<&&<E as ScalarEngine>::Fr> {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `bellman`
```
